const paths = $("#world-map path");
//country names object, coincides with
//classnames given to the individual
//country paths
const names = {
  BD: "Bangladesh",
  BE: "Belgium",
  BF: "Burkina Faso",
  BG: "Bulgaria",
  BA: "Bosnia and Herzegovina",
  BB: "Barbados",
  BL: "Saint-Barthélemy",
  BM: "Bermuda",
  BN: "Brunei",
  BO: "Bolivia",
  JP: "Japan",
  BI: "Burundi",
  BJ: "Benin",
  BT: "Bhutan",
  JM: "Jamaica",
  BW: "Botswana",
  WS: "Samoa",
  BR: "Brazil",
  BS: "Bahamas",
  BY: "Belarus",
  BZ: "Belize",
  TN: "Tunisia",
  RW: "Rwanda",
  RS: "Serbia",
  TL: "Timor-Leste",
  RE: "Reunion (France)",
  TM: "Turkmenistan",
  TJ: "Tajikistan",
  RO: "Romania",
  GW: "Guinea-Bissau",
  GU: "Guam",
  GT: "Guatemala",
  GS: "South Georgia and South Sandwich Islands",
  GR: "Greece",
  GQ: "Equatorial Guinea",
  GP: "Guadeloupe (France)",
  BH: "Bahrain",
  GY: "Guyana",
  GF: "France",
  GE: "Georgia",
  GD: "Grenada",
  GB: "United Kingdom",
  GA: "Gabon",
  GN: "Guinea",
  GM: "The Gambia",
  GL: "Greenland",
  GH: "Ghana",
  OM: "Oman",
  JO: "Jordan",
  HR: "Croatia",
  HT: "Haiti",
  HU: "Hungary",
  HK: "Hong Kong",
  HN: "Honduras",
  VE: "Venezuela",
  PR: "Puerto Rico",
  PS: "Palestine",
  PW: "Palau",
  PT: "Portugal",
  KN: "Saint Kitts and Nevis",
  PY: "Paraguay",
  AI: "Anguilla",
  PA: "Panama",
  PF: "French Polynesia",
  PG: "Papua New Guinea",
  PE: "Peru",
  PK: "Pakistan",
  PH: "Philippines",
  PL: "Poland",
  ZM: "Zambia",
  BQSE: "St. Eustatius (Netherlands)",
  EH: "Western Sahara",
  RU: "Russian Federation",
  EE: "Estonia",
  EG: "Egypt",
  ZA: "South Africa",
  EC: "Ecuador",
  IT: "Italy",
  VN: "Vietnam",
  SB: "Solomon Islands",
  ET: "Ethiopia",
  SO: "Somalia",
  ZW: "Zimbabwe",
  KY: "Cayman Islands",
  ES: "Spain",
  ER: "Eritrea",
  ME: "Montenegro",
  MD: "Moldova",
  MG: "Madagascar",
  MF: "Saint Martin (French)",
  MA: "Morocco",
  MC: "Monaco",
  UZ: "Uzbekistan",
  MM: "Myanmar",
  ML: "Mali",
  MN: "Mongolia",
  MH: "Marshall Islands",
  MK: "Macedonia",
  MU: "Mauritius",
  MT: "Malta",
  MW: "Malawi",
  MV: "Maldives",
  MQ: "Martinique (France)",
  MP: "Northern Mariana Islands",
  MS: "Montserrat",
  MR: "Mauritania",
  UG: "Uganda",
  MY: "Malaysia",
  MX: "Mexico",
  IL: "Israel",
  FR: "France",
  FI: "Finland",
  FJ: "Fiji",
  FK: "Falkland Islands",
  FM: "Micronesia",
  FO: "Faeroe Islands",
  NI: "Nicaragua",
  NL: "Netherlands",
  NO: "Norway",
  NA: "Namibia",
  VU: "Vanuatu",
  NC: "New Caledonia",
  NE: "Niger",
  NG: "Nigeria",
  NZ: "New Zealand",
  BQBO: "Netherlands",
  NP: "Nepal",
  NR: "Nauru",
  XK: "Kosovo",
  CI: "Côte d'Ivoire",
  CH: "Switzerland",
  CO: "Colombia",
  CN: "China",
  CM: "Cameroon",
  CL: "Chile",
  CA: "Canada",
  CG: "Republic of Congo",
  CF: "Central African Republic",
  CD: "Democratic Republic of the Congo",
  CZ: "Czech Republic",
  CY: "Cyprus",
  CR: "Costa Rica",
  CW: "Curaco (Netherlands)",
  CV: "Cape Verde",
  CU: "Cuba",
  SZ: "Swaziland",
  SY: "Syria",
  SX: "Saint Martin (Dutch)",
  KG: "Kyrgyzstan",
  KE: "Kenya",
  SS: "South Sudan",
  SR: "Suriname",
  KI: "Kiribati",
  KH: "Cambodia",
  SV: "El Salvador",
  KM: "Comoros",
  ST: "São Tomé and Principe",
  SK: "Slovakia",
  KR: "South Korea",
  SI: "Slovenia",
  KP: "North Korea",
  KW: "Kuwait",
  SN: "Senegal",
  SL: "Sierra Leone",
  SC: "Seychelles",
  KZ: "Kazakhstan",
  SA: "Saudi Arabia",
  SG: "Singapore",
  SE: "Sweden",
  SD: "Sudan",
  DO: "Dominican Republic",
  DM: "Dominica",
  DJ: "Djibouti",
  DK: "Denmark",
  VG: "British Virgin Islands",
  DE: "Germany",
  YE: "Yemen",
  DZ: "Algeria",
  US: "United States",
  UY: "Uruguay",
  YT: "Mayotte (France)",
  LB: "Lebanon",
  LC: "Saint Lucia",
  LA: "Laos",
  TV: "Tuvalu",
  TW: "Taiwan",
  TT: "Trinidad and Tobago",
  TR: "Turkey",
  LK: "Sri Lanka",
  LI: "Liechtenstein",
  LV: "Latvia",
  TO: "Tonga",
  LT: "Lithuania",
  LU: "Luxembourg",
  LR: "Liberia",
  LS: "Lesotho",
  TH: "Thailand",
  TG: "Togo",
  TD: "Chad",
  TC: "Turks and Caicos Islands",
  LY: "Libya",
  VC: "Saint Vincent and the Grenadines",
  AE: "United Arab Emirates",
  AD: "Andorra",
  AG: "Antigua and Barbuda",
  AF: "Afghanistan",
  IQ: "Iraq",
  VI: "United States Virgin Islands",
  IS: "Iceland",
  IR: "Iran",
  AM: "Armenia",
  AL: "Albania",
  AO: "Angola",
  AS: "American Samoa",
  AR: "Argentina",
  AU: "Australia",
  AT: "Austria",
  AW: "Aruba",
  IN: "India",
  TZ: "Tanzania",
  IC: "Canary Islands (Spain)",
  AZ: "Azerbaijan",
  IE: "Ireland",
  ID: "Indonesia",
  UA: "Ukraine",
  QA: "Qatar",
  MZ: "Mozambique",
};

for (let i = 0; i < paths.length; i++) {
  const country = paths[i];
  country.addEventListener("mouseenter", () => {
    //from https://stackoverflow.com/questions/11373741/detecting-by-how-much-user-has-scrolled
    let scrollLeft =
      window.pageXOffset !== undefined
        ? window.pageXOffset
        : (
            document.documentElement ||
            document.body.parentNode ||
            document.body
          ).scrollLeft;
    const bounds = country.getBoundingClientRect();
    const tooltip = document.getElementById("tooltip");
    //get corresponding name
    const code = country.className.baseVal.slice(-2);
    tooltip.innerHTML = names[code];
    //set our width, height and position
    tooltip.style.visibility = "visible";
    tooltip.style.top = `${bounds.y + bounds.height / 2 - 5}px`;
    tooltip.style.left = `${bounds.x + bounds.width / 2 - 5 + scrollLeft}px`;
  });
  country.addEventListener("mouseleave", () => {
    const tooltip = document.getElementById("tooltip");
    tooltip.style.visibility = "hidden";
  });
}
